[build]
  publish = "."
    functions = "netlify/functions"

    [functions."parse-labels"]
      timeout = 26

      [[redirects]]
        from = "/api/*"
          to = "/.netlify/functions/:splat"
            status = 200
